# promotion-service.yml
# 促銷服務配置：限時特賣、行銷活動、價格計算

server:
  port: 9010
  tomcat:
    threads:
      max: 120
      min-spare: 20
    max-connections: 3000
    accept-count: 300

spring:
  # ==================== 資料庫連線 ====================
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:mall_promotion}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Taipei&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=256&prepStmtCacheSqlLimit=2048
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: promotion-hikari
      maximum-pool-size: 40
      minimum-idle: 20
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 10000
  
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: 2000ms
  
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 8
        prefetch: 10

  # ==================== Feign 遠端呼叫配置 ====================
  # 用於呼叫 product-service 取得商品資訊（價格計算、規格查詢）
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 3000
            logger-level: BASIC
          product-service:
            connect-timeout: 1000
            read-timeout: 3000
            logger-level: BASIC

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URI:http://auth-service:9000}/oauth2/jwks

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # log-impl 已移除：StdOutImpl 在高併發下嚴重影響效能
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  group-configs:
    - group: promotion-service
      paths-to-match: "/**"
      packages-to-scan: com.nameless.mall.promotion.controller

# circuitbreaker 由 application.yml 的 spring.cloud.sentinel.feign.enabled 統一管理

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    com.nameless.mall.promotion: INFO
    org.springframework.security: WARN

